services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 6500:5432
    env_file:
      - ./app.env
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 5050:80
    env_file:
      - ./pgadmin.env
  gist-backend:
    depends_on:
      - postgres
    restart: on-failure
    image: yvyom/github-gist-backend:v1.0-alpha
    pull_policy: if_not_present
    container_name: gist-backend
    ports:
      - 8000:8000
    volumes:
      - ./app.env:/app/env/app.env
volumes:
  postgres:
