// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/forgotpassword": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Send reset code for password reset",
                "parameters": [
                    {
                        "description": "The Input for sending password reset code",
                        "name": "ForgotPasswordInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ForgotPasswordInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/auth/github/callback": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register a new user through GitHub",
                "parameters": [
                    {
                        "type": "string",
                        "description": "code received from GitHub API after user authorizes application",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "new username to be used for the user",
                        "name": "newUsername",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AccessCodeResponseWrapper"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.AccessCodeResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/auth/github/clientid": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Get GitHub Client ID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GitHubClientIdResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Sign in a user",
                "parameters": [
                    {
                        "description": "Sign in a user",
                        "name": "SignInInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SignInInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AccessCodeResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Log out a user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponseWrapper"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Refresh access token with refresh token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AccessCodeResponseWrapper"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User object that needs to be added to the system",
                        "name": "SignUpInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SignUpInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/auth/resendverificationemail": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Resend verification email",
                "parameters": [
                    {
                        "description": "Resend verification email to the user with the given email",
                        "name": "ResendVerificationEmailInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ResendVerificationEmailInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/auth/resetpassword": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Reset password",
                "parameters": [
                    {
                        "description": "The input required to reset the password",
                        "name": "ResetPasswordInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ResetPasswordInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "The username of the user",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The token required to reset the password",
                        "name": "resetToken",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/auth/usernameavailable/{username}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Check if username is available",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The username to check availability",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponseWrapper"
                        }
                    }
                }
            }
        },
        "/auth/verifyemail": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Verify users email address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username of the user to be verified",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Verify the added user object to the database",
                        "name": "verificationCode",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/gists/{gistId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gist Operations"
                ],
                "summary": "Get the gist by gist id, DOES NOT load gist comments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The ID of the gist",
                        "name": "gistId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GistWithoutCommentsWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/gists/{gistId}/comments": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gist Operations"
                ],
                "summary": "Get the comments of a gist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The ID of the gist",
                        "name": "gistId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CommentArrayWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/gists/{gistId}/stargazers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gist Operations"
                ],
                "summary": "Get the stargazers of a gist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The ID of the gist",
                        "name": "gistId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StringArrayWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Check the basic health of api",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/comments": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Operations"
                ],
                "summary": "Create a comment on a gist",
                "parameters": [
                    {
                        "description": "The Input for creating comment",
                        "name": "CreateCommentInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CommentOnGistRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.CommentWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/users/details": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Operations"
                ],
                "summary": "Update user metadata",
                "parameters": [
                    {
                        "description": "The Input for updating user metadata",
                        "name": "UpdateUserDetailsInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUserDetailsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserMetadataWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/users/follow/{userToFollow}": {
            "patch": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Operations"
                ],
                "summary": "Follow a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The username of the user to follow",
                        "name": "userToFollow",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/users/gists": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Operations"
                ],
                "summary": "Create a gist",
                "parameters": [
                    {
                        "description": "The Input for creating gist",
                        "name": "CreateGistInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateGistRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.GistWithoutCommentsWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Operations"
                ],
                "summary": "Update gist data",
                "parameters": [
                    {
                        "description": "The Input for updating user gist",
                        "name": "UpdateGistInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateGistRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GistWithoutCommentsWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/users/gists/{gistId}/star": {
            "patch": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Operations"
                ],
                "summary": "Star a gist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The ID of the gist to star",
                        "name": "gistId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/users/gists/{gistId}/unstar": {
            "patch": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Operations"
                ],
                "summary": "Un-star a gist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The ID of the gist to un-star",
                        "name": "gistId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Operations"
                ],
                "summary": "Get the current logged in user details.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserResponseWrapper"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/users/unfollow/{userToUnfollow}": {
            "patch": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Operations"
                ],
                "summary": "Unfollow a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The username of the user to unfollow",
                        "name": "userToUnfollow",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/users/{username}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Operations"
                ],
                "summary": "Get the publicly visible details of a user, DOES NOT load gists",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The username to get",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PublicUserProfileResponseWrapper"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/users/{username}/followers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Operations"
                ],
                "summary": "Get the followers of a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The username of the user to get the followers of",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StringArrayWrapper"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/users/{username}/following": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Operations"
                ],
                "summary": "Get the list of users a user is following",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The username of the user to get the following of",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StringArrayWrapper"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/users/{username}/follows/{otherUser}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Operations"
                ],
                "summary": "Whether a username follows another username",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The username of the follower",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The username of the user being followed",
                        "name": "otherUser",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BooleanResponseWrapper"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/users/{username}/gistIds": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Operations"
                ],
                "summary": "Get the publicly visible gist Ids of a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The username to get gists for",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UUIDArrayWrapper"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/users/{username}/gists": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Operations"
                ],
                "summary": "Get the publicly visible gists of a user, DOES NOT load the gist comments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The username to get gists for",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GistWithoutCommentsArrayWrapper"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        },
        "/users/{username}/starredGist/{gistId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Operations"
                ],
                "summary": "Whether a user has starred a gist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The username of the user to check the starred gist of",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The ID of the gist to check if it is starred",
                        "name": "gistId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BooleanResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.BooleanResponseWrapper"
                        }
                    }
                }
            }
        },
        "/users/{username}/starredGists": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Operations"
                ],
                "summary": "Get the list of starred gists of a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The username of the user to get the starred gists of",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UUIDArrayWrapper"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseWrapper"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AccessCodeResponse": {
            "type": "object",
            "properties": {
                "access_code": {
                    "type": "string"
                }
            }
        },
        "models.AccessCodeResponseWrapper": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.AccessCodeResponse"
                }
            }
        },
        "models.BooleanResponse": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "boolean"
                }
            }
        },
        "models.BooleanResponseWrapper": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.BooleanResponse"
                }
            }
        },
        "models.Comment": {
            "type": "object",
            "properties": {
                "commentID": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "gistID": {
                    "description": "Foreign Key",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.CommentArrayWrapper": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Comment"
                    }
                }
            }
        },
        "models.CommentOnGistRequest": {
            "type": "object",
            "required": [
                "content",
                "gistId"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "gistId": {
                    "type": "string"
                }
            }
        },
        "models.CommentWrapper": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.Comment"
                }
            }
        },
        "models.CreateGistRequest": {
            "type": "object",
            "required": [
                "content",
                "name",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "private": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                }
            }
        },
        "models.ErrorResponseWrapper": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.ErrorResponse"
                }
            }
        },
        "models.ForgotPasswordInput": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "models.Gist": {
            "type": "object",
            "properties": {
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Comment"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "gistContent": {
                    "$ref": "#/definitions/models.GistContent"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "description": "We are hard-coding in logic to make sure name is unique across all gists of a user",
                    "type": "string"
                },
                "private": {
                    "type": "boolean"
                },
                "starCount": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "description": "Foreign Key",
                    "type": "string"
                }
            }
        },
        "models.GistContent": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "description": "Foreign Key",
                    "type": "string"
                }
            }
        },
        "models.GistWithoutComments": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "gistContent": {
                    "$ref": "#/definitions/models.GistContent"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "description": "We are hard-coding in logic to make sure name is unique across all gists of a user",
                    "type": "string"
                },
                "private": {
                    "type": "boolean"
                },
                "starCount": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.GistWithoutCommentsArrayWrapper": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.GistWithoutComments"
                    }
                }
            }
        },
        "models.GistWithoutCommentsWrapper": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.GistWithoutComments"
                }
            }
        },
        "models.GitHubClientIdResponse": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                }
            }
        },
        "models.GitHubClientIdResponseWrapper": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.GitHubClientIdResponse"
                }
            }
        },
        "models.PublicUserProfileResponse": {
            "type": "object",
            "properties": {
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "userMetadata": {
                    "$ref": "#/definitions/models.UserMetadata"
                },
                "username": {
                    "type": "string"
                },
                "verified": {
                    "type": "boolean"
                }
            }
        },
        "models.PublicUserProfileResponseWrapper": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.PublicUserProfileResponse"
                }
            }
        },
        "models.ResendVerificationEmailInput": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "models.ResetPasswordInput": {
            "type": "object",
            "required": [
                "password",
                "passwordConfirm"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "passwordConfirm": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "models.SignInInput": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.SignUpInput": {
            "type": "object",
            "required": [
                "email",
                "firstName",
                "lastName",
                "password",
                "passwordConfirm",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "passwordConfirm": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.StringArrayWrapper": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                }
            }
        },
        "models.SuccessResponseWrapper": {
            "type": "object",
            "properties": {
                "success": {
                    "$ref": "#/definitions/models.SuccessResponse"
                }
            }
        },
        "models.UUIDArrayWrapper": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.UpdateGistRequest": {
            "type": "object",
            "required": [
                "gistId"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "gistId": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "private": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.UpdateUserDetailsRequest": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string"
                },
                "profilePicture": {
                    "type": "string"
                },
                "statusIcon": {
                    "type": "string"
                },
                "tagline": {
                    "type": "string"
                },
                "twitter": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "models.UserMetadata": {
            "type": "object",
            "properties": {
                "followers": {
                    "type": "integer"
                },
                "following": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "profilePicture": {
                    "type": "string"
                },
                "starredGistsCount": {
                    "type": "integer"
                },
                "statusIcon": {
                    "type": "string"
                },
                "tagline": {
                    "type": "string"
                },
                "twitter": {
                    "type": "string"
                },
                "username": {
                    "description": "Foreign Key",
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "models.UserMetadataWrapper": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.UserMetadata"
                }
            }
        },
        "models.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gists": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Gist"
                    }
                },
                "lastName": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "userMetadata": {
                    "$ref": "#/definitions/models.UserMetadata"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UserResponseWrapper": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.UserResponse"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0-alpha",
	Host:             "",
	BasePath:         "/api/",
	Schemes:          []string{},
	Title:            "GitHub Gist Backend REST API",
	Description:      "The REST API for GitHub Gist Backend",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
