basePath: /api/
definitions:
  models.ForgotPasswordInput:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  models.ResendVerificationEmailInput:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  models.ResetPasswordInput:
    properties:
      password:
        minLength: 8
        type: string
      passwordConfirm:
        minLength: 8
        type: string
    required:
    - password
    - passwordConfirm
    type: object
  models.SignInInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.SignUpInput:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        minLength: 8
        type: string
      passwordConfirm:
        type: string
      username:
        type: string
    required:
    - email
    - firstName
    - lastName
    - password
    - passwordConfirm
    - username
    type: object
info:
  contact: {}
  description: The REST API for GitHub Gist Backend
  title: GitHub Gist Backend REST API
  version: 1.0-alpha
paths:
  /auth/forgotpassword:
    post:
      consumes:
      - application/json
      parameters:
      - description: The Input for sending password reset code
        in: body
        name: ForgotPasswordInput
        required: true
        schema:
          $ref: '#/definitions/models.ForgotPasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Send reset code for password reset
      tags:
      - Authentication
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Sign in a user
        in: body
        name: SignInInput
        required: true
        schema:
          $ref: '#/definitions/models.SignInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Sign in a user
      tags:
      - Authentication
  /auth/logout:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Log out a user
      tags:
      - Authentication
  /auth/refresh:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Refresh access token with refresh token
      tags:
      - Authentication
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User object that needs to be added to the system
        in: body
        name: SignUpInput
        required: true
        schema:
          $ref: '#/definitions/models.SignUpInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
        "502":
          description: Bad Gateway
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - Authentication
  /auth/resendverificationemail:
    post:
      consumes:
      - application/json
      parameters:
      - description: Resend verification email to the user with the given email
        in: body
        name: ResendVerificationEmailInput
        required: true
        schema:
          $ref: '#/definitions/models.ResendVerificationEmailInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Resend verification email
      tags:
      - Authentication
  /auth/resetpassword/{resetToken}:
    patch:
      consumes:
      - application/json
      parameters:
      - description: The input required to reset the password
        in: body
        name: ResetPasswordInput
        required: true
        schema:
          $ref: '#/definitions/models.ResetPasswordInput'
      - description: The token required to reset the password
        in: path
        name: resetToken
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Reset password
      tags:
      - Authentication
  /auth/usernameavailable/{username}:
    get:
      parameters:
      - description: The username to check availability
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Check if username is available
      tags:
      - Authentication
  /auth/verifyemail/{verificationCode}:
    get:
      parameters:
      - description: Verify the added user object to the database
        in: path
        name: verificationCode
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Verify users email address
      tags:
      - Authentication
  /health:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Check the basic health of api
      tags:
      - Health
  /users/me:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get the current logged in user details.
      tags:
      - User Operations
swagger: "2.0"
